version: '3.8'

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: fluxpulse-release-dashboard:latest
    ports:
      - "4000:4000"
    environment:
      CF_GH_PAT_FluxPulseReleaseDashboard: ${GH_PAT}
      PORT: "4000"
    restart: unless-stopped
    container_name: fluxpulse-release-dashboard
    labels:
      com.docker.compose.project: "fluxpulse"
      service.name: "Release Dashboard"
      service.group: "fluxpulse"
